// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		
		int bigger= 0;
		int smaller = 0;
		int i =0;
		while (i<N) {
			double random = Math.random();
			i++;
			if ( random >= 0.5){
					bigger +=1;
			}
			else {
				smaller +=1;
			}
		}

		double ratio =(double) smaller /(double) bigger ;
		
		System.out.println("> 0.5: " + smaller + " times");
		
		System.out.println("<= 0.5: " + bigger + " times");
		
		if (bigger != 0 && smaller != 0){
			System.out.println("Ratio: " + ratio);
		}
		
	}
}
